
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Aug 20 18:11:17 CEST 2015
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MAQ = 28;
  public static final int NUMERO = 36;
  public static final int MASMAS = 19;
  public static final int MENOSMENOS = 20;
  public static final int AC = 2;
  public static final int POR = 5;
  public static final int UMINUS = 26;
  public static final int FOR = 18;
  public static final int CP = 10;
  public static final int NUMEROF = 37;
  public static final int NOT = 23;
  public static final int AND = 33;
  public static final int CL = 7;
  public static final int OR = 34;
  public static final int DIV = 24;
  public static final int CC = 3;
  public static final int IF = 11;
  public static final int MAOQ = 30;
  public static final int EOF = 0;
  public static final int ASIG = 8;
  public static final int error = 1;
  public static final int MENOS = 22;
  public static final int MOD = 25;
  public static final int NEQ = 32;
  public static final int IDENT = 38;
  public static final int EQ = 31;
  public static final int MEQ = 27;
  public static final int ELSE = 12;
  public static final int TO = 15;
  public static final int WHILE = 14;
  public static final int DOWNTO = 17;
  public static final int AP = 9;
  public static final int PRINT = 35;
  public static final int DO = 13;
  public static final int MEOQ = 29;
  public static final int STEP = 16;
  public static final int AL = 6;
  public static final int PYC = 4;
  public static final int MAS = 21;
}

